Instructions for running on windows
acvigue/jellyseer pull request #61
Opened 2021-07-16 00:34 UTC by DevilsDesigns

- Added some UI Edits 
- added Jellyfin to listed support
- added Windows Autostart Instructions
- added Windows Building instructions
- added Running Overseerr on Windows with Jellyfin Support

#### Description

#### Screenshot (if UI-related)

#### To-Dos

- [ ] Successful build `yarn build`
- [ ] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #XXXX

2021-07-16 02:39 UTC, acvigue requested changes

2021-07-16 02:39 UTC, acvigue commented on README.md
> +1. Git Bash **[Git Direct Downoad](https://git-scm.com/download/win)**
typo, also users installing DEV software, are expected to know how to use git, we don't need this.

2021-07-16 02:39 UTC, acvigue commented on README.md
> +2. NodeJs [NodeJS Direct x64 Download](https://nodejs.org/dist/v14.17.3/node-v14.17.3-x64.msi)** **[NodeJS Direct x86 Download](https://nodejs.org/dist/v14.17.3/node-v14.17.3-x86.msi)**
again, this is a node app, should be left as an exercise to the reader, also, why not use chocolatey?

2021-07-16 02:39 UTC, acvigue commented on README.md
> +MAKE SURE YOU HAVE ALL WINDWOS UPDATE PENDED AND AFTER INSTALLING THE PROGRAMS ABOVE RESTART THE OS BEFORE CONTINUE FOR GOOD MEASURES.
why? common sense.

2021-07-16 02:39 UTC, acvigue commented on README.md
> +1. Open Powershell with administrative rights.
again, common sense

2021-07-16 02:39 UTC, acvigue commented on README.md
> +2. Get yarn by typing in powershell `npm install --global yarn`
choco.

2021-07-16 02:39 UTC, acvigue commented on README.md
> +3. Now run in powershell `npm install -g win-node-env` so it can correctly build for windows.
add it to package.json

2021-07-16 02:39 UTC, acvigue commented on README.md
> +5. Go to a directory where you want your app to run. I normally run all binaries in `C:\Tools\(appname)` so mine is C:\Tools
users don't care about _your_ install location, they will install it wherever they want, also, misleading, this isn't a binary.

2021-07-16 02:39 UTC, acvigue commented on README.md
> +4. Once yarn is installed close powershell and open a new powershell with adminstrative privelages.
preferred verbiage: refresh your console

2021-07-16 02:39 UTC, acvigue commented on README.md
> +6. Then run `git clone https://github.com/sct/overseerr.git`
wrong repo.

2021-07-16 02:39 UTC, acvigue commented on README.md
> +7. Then once cloned youll see it ripped a new folder in `C:\Tools` its a folder called `overseerr`
we're not checking out a branch? this won't work

2021-07-16 02:39 UTC, acvigue commented on README.md
> +7. Then once cloned youll see it ripped a new folder in `C:\Tools` its a folder called `overseerr`
ripped? we ain't handbrake :p

2021-07-16 02:39 UTC, acvigue commented on README.md
> +8. Now open the folder overseerr directory in powershell by running `cd C:\Tools\overseerr`
misleading again, don't assume users are using C:\Tools. just use a relative path from PWD?

2021-07-16 02:39 UTC, acvigue commented on README.md
> +9. once in the directory `C:\Tools\overseerr` run `yarn`
again. also, no command explanation.

2021-07-16 02:39 UTC, acvigue commented on README.md
> +10. Then once finished (it will take a bit of a long time) run `yarn build`
"build the application with `yarn build`, or if attempting to start a dev environment, run the `yarn dev` command

2021-07-16 02:39 UTC, acvigue commented on README.md
> +## Auto-Start at Windows Startup
This is a project README, not a tutorials site, why are we explaining something that could be accomplished from a quick google search of "run cmd on autostart w10"
Also, no native Services??

2021-07-16 02:39 UTC, acvigue commented on README.md
> +## Setup NSSM with Overserr
again, outside of scope of this tutorial.

2021-07-16 02:39 UTC, acvigue commented on README.md
> +7. Open up a powershell as administrator and run nssm start Overseerr or go to services.msc and find overseerr task and right click and select start
L63-79 refer to above comment.

2021-07-16 02:39 UTC, acvigue commented on README.md
fork notice?

2021-07-16 02:39 UTC, acvigue commented on README.md
> +7. Then once cloned youll see it ripped a new folder in `C:\Tools` its a folder called `overseerr`
typo

2021-07-21 00:33 UTC, DevilsDesigns commented on README.md
> +7. Then once cloned youll see it ripped a new folder in `C:\Tools` its a folder called `overseerr`
i apologize I have dislexia and have a hard time finding typos. Can you specify where?

2021-07-21 00:33 UTC, DevilsDesigns commented on README.md
? i dont understand can you eleborate?

2021-07-21 00:34 UTC, DevilsDesigns commented on README.md
> +## Setup NSSM with Overserr
yes i will make the edits. I have yet to find a way to auto run on windows. I thought i edited this out. I apologize

2021-07-21 00:35 UTC, DevilsDesigns commented on README.md
> +2. Get yarn by typing in powershell `npm install --global yarn`
no npm is the installer i used. Choco was malfunctioning when i would install it and set the path

2021-07-21 00:37 UTC, DevilsDesigns commented on README.md
> +MAKE SURE YOU HAVE ALL WINDWOS UPDATE PENDED AND AFTER INSTALLING THE PROGRAMS ABOVE RESTART THE OS BEFORE CONTINUE FOR GOOD MEASURES.
because I had a pending update and my powershell and overseerr were failing build and pull thats why I couldnt understand why i kept getting erros when running Yarn start or yarn build. Once i restarted all ran succesfully. I would prefer to keep this as it could have saved me many hours of troubleshooting. I was thrown crazy errors that nothing would fix or thee was not any relative information that could be applied.

2021-07-21 00:39 UTC, DevilsDesigns commented on README.md
> +2. NodeJs [NodeJS Direct x64 Download](https://nodejs.org/dist/v14.17.3/node-v14.17.3-x64.msi)** **[NodeJS Direct x86 Download](https://nodejs.org/dist/v14.17.3/node-v14.17.3-x86.msi)**
Just trust me. I love choco but with windows their Enviroments with choco in powershell have alot of issues. The only way i was able to build and run  Jellyseer was to use the stock .exe from the distributor of the app. Choco threw me a bunch of errors everytime i couldnt pinpoint why. So i eneded up deinstalling all choco and reinstall exe. Worked first time

2021-07-21 00:40 UTC, DevilsDesigns commented on README.md
> +1. Git Bash **[Git Direct Downoad](https://git-scm.com/download/win)**
okay will do do you want me to still list it as a requirment but without the install?

2021-07-21 00:59 UTC, DevilsDesigns commented on README.md
> +1. Git Bash **[Git Direct Downoad](https://git-scm.com/download/win)**
Doesnt it still have plex support? i saw on the localhost:5055 that their is still a plex login method is that not working

2021-07-21 00:59 UTC, DevilsDesigns commented on README.md
> +3. Now run in powershell `npm install -g win-node-env` so it can correctly build for windows.
? Does this mean you are going to add it to package.json?

2021-07-21 00:59 UTC, DevilsDesigns commented on README.md
> +5. Go to a directory where you want your app to run. I normally run all binaries in `C:\Tools\(appname)` so mine is C:\Tools
i understand that but its for examples. I know whenever i follow installations especially when i was new to github i would have a hard time understanding why and where i was installing it to. This is a way to combat that confusion. If you would like me to remove thats fine i will do so. But i had a reason to put this example in there.

2021-07-21 00:59 UTC, DevilsDesigns commented on README.md
> +7. Then once cloned youll see it ripped a new folder in `C:\Tools` its a folder called `overseerr`
> 
> 
> we're not checking out a branch? this won't work

i dont understand it unzips a folder to the main directory called overseerr. I can change it to say unzips the git to a sub folder called overseerr

2021-07-21 00:59 UTC, DevilsDesigns commented on README.md
> +9. once in the directory `C:\Tools\overseerr` run `yarn`
? Do you want me to add a command explanation or are you telling me to remove the first part of `once in the directory xxxxxxxxxx`

2021-07-21 00:59 UTC, DevilsDesigns commented on README.md
> +10. Then once finished (it will take a bit of a long time) run `yarn build`
is this the exact edit you would like?

2021-07-21 00:59 UTC, DevilsDesigns commented on README.md
> +## Auto-Start at Windows Startup
??? Could you explain sorry. I dont understand i attempted to get autostarting working but have failed to do so. Could you specify exactly how to autostart jellyseerr on Windows 10 Boot or login

2021-07-21 00:59 UTC, DevilsDesigns commented on README.md
> +6. Then run `git clone https://github.com/sct/overseerr.git`
fixed

2021-08-01 22:12 UTC, closed without merging